services:
  - type: web
    name: instagram-music-bot
    runtime: python
    pythonVersion: 3.11
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    
    startCommand: python3 bot.py
    
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8595539202:AAHNkg-oExRsd6RdQXpEao-KfU6zhfOO4SY
    
    plan: free
    
    # Disk va memory sozlamalari
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
